title:   Kafayat Balogun
logo: "/images/Profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 My name is Kafayat, inspire Business Intelligence/ data Analyst with over  5-years experience in public financial planning, budgetary, monitoring and reporting on public funded programs, I have 5year Accounting university knowledge and currently a student of business intelligence/data analyst.  I am passionate about diving in data, solving problems and data transformation. 
  <br><br>
  <a href="http://www.linkedin.com/in/kafayat-balogun-703101175l/">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://public.tableau.com/app/profile/kafayat4339/">View My Tableau Work Samples</a>
  <br><br>
  <a href="https://www.notion.so/kafayatbalogun/Portfolio-Kafayat-Balogun-c626bc1f611b4b8ca2935261d2596ddc?showMoveTo=true">View My Notion Portfolios</a>
  
theme: jekyll-theme-minimal 
 
